all:
	arm-unknown-linux-gnu-gcc -o lab3 lab3.c \
		-L /opt/arm-unknown-linux-gnu/arm-unknown-linux-gnu/lib/ \
		-I /opt/arm-unknown-linux-gnu/arm-unknown-linux-gnu/include/ \
		-I /home/ray/microtime/linux/include/
clean:
	rm lab3